#!/bin/bash -e
cd "$(git rev-parse --show-toplevel)"

[[ $FORK ]] || FORK='https://github.com/amerlyq'

sed -i '/^###GEN###$/q' .gitignore
_ignore(){ printf "/%s/\n" "$@" >> .gitignore; }
creds(){ ! hash 'r.git-my-repo' &>/dev/null || (cd "${1:?}" && r.git-my-repo); }
hide_b(){ ! git branch -r | grep -qF origin/${1:?} || git branch -dr origin/$1; }

clone(){ [[ -d ${2:?} ]] || { mkdir -p "$2"; git clone "$@"; }; creds "$2" && _ignore "$2"; }
orphan(){ clone "$FORK/forestanza" "${1:?}" --single-branch -b ${3:-${1##*/}}; }
extern(){ clone "${1:?}" "ext/${1##*/}" --depth=1 --single-branch -b ${3:-master}; }
filedl(){ local d=ext/${2:?} url="https://raw.githubusercontent.com/${1:?}"
  curl --create-dirs -o "${d:?}/${1##*/}" "${url:?}" && _ignore "$d"; }

## Main
creds "$PWD"
hide_b note
hide_b gh-pages

## Supplement
orphan doc -- note
# orphan site/content
# orphan site/doc
orphan site/gh-pages

## Own deps
clone "$FORK/forestanza-db" db
clone "$FORK/aeternum-cmake-cross" cmake
clone "$FORK/aeternum-jekyll-offline" site/template

## External deps
extern 'https://github.com/whoshuu/cpr'
extern 'https://github.com/JosephP91/curlcpp'

filedl 'nlohmann/json/develop/src/json.hpp' json
# ALT:(release) https://github.com/nlohmann/json/releases/download/v2.0.1/json.hpp
# ALT:(90MB) extern 'https://github.com/nlohmann/json'
